import Head from "next/head";
import Menu from "./menu"
import style from "../styles/layout.module.css";



export default function Layout({ children, title }) {
    return (
    <div>
        <Head>
            <title>Qatar World Cup Merch {title ? ` | ${title}` : ""}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Menu />
         <div className={style.container}>
            {children}
        </div> 
    </div>

    );
} //children viene por defecto en los componentes Next . Este componente cambia de titulo dependiendo donde estoy parado
//el ternario dentro de <title> es para validar si title existe, en ese caso mandarlo como parametro de Layout
//el children es para que se rendericen los componenetes dentro de layout
//borro todo el contenido de index , y ahi mismo llamo a este componenete Layout