import Head from 'next/head' ;//PRIMER COMPONENTE QUE SE RENDERIZA
import Image from 'next/image';
import Link from 'next/link'; //importamos para hacer el routeo
import styles from '../styles/Home.module.css';

//si aparece un error Link-<a> child, usar legacyBehavior dentro del Link y lesto

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link legacyBehavior href="/faq"> 
          <a>
            FAQ
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
